export const af_events = {
  af_add_to_cart: 'af_add_to_cart',
  af_initiated_checkout: 'af_initiated_checkout',
  af_purchase: 'af_purchase',
};

export const af_property = {
  af_revenue: 'af_revenue',
  af_price: 'af_price',
  af_quantity: 'af_quantity',
  af_param_1: 'af_param_1',
  af_param_2: 'af_param_2',
  af_param_3: 'af_param_3',
  af_param_4: 'af_param_4',
  af_param_5: 'af_param_5',
  af_city: 'af_city',
  af_customer_user_id: 'af_customer_user_id',
  af_adrev_network_name: 'af_adrev_network_name',
  af_adrev_placement_id: 'af_adrev_placement_id',
  af_adrev_ad_type: 'af_adrev_ad_type',
};

export const amplitude_events = {
  view_screen: 'View Screen',
  search: 'Search',
  view_details: 'View Details',
  phone_number_added: 'Phone Number Added',
  whatsapp_added: 'Whatsapp Added',
  city_selected: 'City Selected',
  add_to_whishlist: 'Add To Whishlist',
  add_to_cart: 'Add To Cart',
  email_added: 'Email Added',
  initiate_checkout: 'Initiate Checkout',
  address_added: 'Address Added',
  purchase_completed: 'Purchase Completed',
};

export const amplitude_property = {
  screen_name: 'Screen Name',
  utm_source: 'UTM Source',
  utm_adset: 'UTM Adset',
  utm_campaign: 'UTM Campaign',
  avg_duration: 'Avg Duration',
  user_id: 'User Id',
  search_term: 'Search term',
  trending_search_term: 'Trending Search Term',
  product_category: 'Product Category',
  product_type: 'Product Type',
  product_label: 'Product Label',
  product_name: 'Product Name',
  product_rent: 'Product Rent',
  page_path: 'Page Path',
  rent_period: 'Rent Period',
  product_tenure: 'Product Tenure',
  phone_number: 'Phone Number',
  city_name: 'City Name',
  add_ons_name: 'Add Ons Name',
  add_ons_rent: 'Add Ons Rent',
  add_ons_rent_period: 'Add Ons Rent Period',
  number_of_items: 'Number Of Items',
  total_cart_value: 'Total Cart Value',
  subscription_type: 'Subscription Type',
  city_shield_added: 'City Shield Added',
  email: 'Email',
  name: 'Name',
  city: 'City',
  state: 'State',
  postal_code: 'Postal Code',
  alternate_phone: 'Alternate Phone',
  promo_code: 'Promo Code',
  cart_value: 'Cart Value',
  code_applied: 'Code Applied',
  discount_value: 'Discount Value',
};
